# Generated by Django 2.1.2 on 2018-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateperpage',
            name='rppBW',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='rateperpage',
            name='rppC',
            field=models.FloatField(default=5),
        ),
    ]
