# Generated by Django 2.1.2 on 2018-10-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('colour', models.BooleanField(default=False)),
                ('copies', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
