# Generated by Django 2.1.2 on 2018-10-16 10:46

import Eprint_users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('document', models.FileField(upload_to='media/documents/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('colour', models.BooleanField(default=False)),
                ('copies', models.SmallIntegerField(default=1)),
                ('task_by', models.ForeignKey(on_delete=models.SET(Eprint_users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
