# Generated by Django 2.1.2 on 2018-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileToPrint', models.FileField(upload_to='')),
                ('colour', models.BooleanField()),
            ],
        ),
    ]
