# Generated by Django 2.1.2 on 2018-10-15 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eprint_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='PrintDocs',
        ),
    ]
