# Generated by Django 2.1.2 on 2018-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='printdocs',
            name='num_pages',
            field=models.SmallIntegerField(default=1),
        ),
    ]
