# Generated by Django 2.1.2 on 2018-10-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0006_auto_20181020_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='printdocs',
            name='file_name',
            field=models.CharField(default='no_name_given', max_length=500),
        ),
    ]
