# Generated by Django 2.1.2 on 2018-10-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0007_printdocs_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='printdocs',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
