# Generated by Django 2.1.2 on 2018-11-10 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0009_printdocs_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hash_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
