# Generated by Django 2.1.3 on 2018-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0010_profile_hash_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printdocs',
            options={'verbose_name': 'Document'},
        ),
        migrations.AddField(
            model_name='printdocs',
            name='order_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
