# Generated by Django 2.1.3 on 2019-03-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0014_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
