# Generated by Django 2.1.3 on 2019-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0015_profile_is_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_high_prt',
            field=models.BooleanField(default=False),
        ),
    ]
